name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwoff1 \
            libopus0 \
            libvpx7 \
            libevent-2.1-7 \
            libflite1 \
            libharfbuzz-icu0 \
            libgstreamer-gl1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libgstreamer-plugins-good1.0-0 \
            libgstreamer1.0-0 \
            libhyphen0 \
            libgles2

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Lint code with ESLint
        run: npx eslint .

      - name: Format code with Prettier
        run: npx prettier --check .

      - name: Run Playwright tests
        run: npx playwright test
